name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Percy
        run: npm install --save-dev @percy/cli @percy/cypress
      
      - name: Run Cypress tests with Percy
        run: npx percy exec -- cypress run --headless
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
